apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: instagram-clone
data:
  DB_HOST: "10.133.1.2"
  DB_PORT: "5432"
  DB_NAME: "instagram"
  REDIS_HOST: "10.133.0.4"
  REDIS_PORT: "6379"
  GCS_BUCKET_NAME: "instagram-clone-prod-media"
  SPRING_PROFILES_ACTIVE: "default"
  LOG_LEVEL: "INFO"
  CORS_ALLOWED_ORIGINS: "*"
  JWT_EXPIRATION: "86400000"
  SERVER_PORT: "8080"
